<a href="https://colab.research.google.com/github/vaibhavkatex/The-Internship-2026/blob/main/Tasks/Session%2013/frist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Session 13 (AIML) - Assignment
Questiont**

*Q1. (Basic Array Creation)
Write a program to:
a) Create a 1D array with elements [10, 20, 30, 40, 50] using np.array().
b) Create a 2D array (3x3) using np.array().
Print both arrays along with their shape and data type (dtype).*

In [ ]:
# Importing a Numpy

import numpy as np

In [ ]:
# Creating a 1D array
array1 =np.array([10, 20, 30, 40, 50])
array1


array([10, 20, 30, 40, 50])

In [ ]:
# Creating a 2D array (3 x 3)
array2 = np.array([[1,2,3],[4,5,6],[6,7,8]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

*Q2. (np.zeros() and np.ones())
Create the following using NumPy:
a) A 1D array of 8 zeros.
b) A 2D array of shape (4, 4) filled with ones.
c) A 3x3 matrix of zeros.
Print all arrays with proper labels.*

In [13]:
# Inport a Numpy as np
import numpy as np

In [14]:
# Creating A 1D array of 8 zeros.
Array1 = np.zeros(8)
Array1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# Creating A 2D array of shape (4, 4) filled with ones.
Array2 =np.ones(16).reshape(4,4)
Array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# Creating a A 3x3 matrix of zeros.
Array3 = np.zeros(9).reshape(3,3)
Array3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

*Q3. (np.arange())
Use np.arange() to create and print the following arrays:
a) Numbers from 0 to 20 (step 1).
b) Even numbers from 10 to 50.
c) Numbers from 5 to 100 with step of 5.*

In [18]:
# Numbers from 0 to 20 (step 1).
Array4 = np.arange(0,20)
Array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
# Even numbers from 10 to 50.
Array5 = np.arange(2,50,2)
Array5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [25]:
# Numbers from 5 to 100 with step of 5.
Array6 = np.arange(5,100,5)
Array6

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])