<a href="https://colab.research.google.com/github/vaibhavkatex/The-Internship-2026/blob/main/Tasks/Session%2013/frist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Session 13 (AIML) - Assignment
Questiont**

*Q1. (Basic Array Creation)
Write a program to:
a) Create a 1D array with elements [10, 20, 30, 40, 50] using np.array().
b) Create a 2D array (3x3) using np.array().
Print both arrays along with their shape and data type (dtype).*

In [ ]:
# Importing a Numpy

import numpy as np

In [ ]:
# Creating a 1D array
array1 =np.array([10, 20, 30, 40, 50])
array1


array([10, 20, 30, 40, 50])

In [ ]:
# Creating a 2D array (3 x 3)
array2 = np.array([[1,2,3],[4,5,6],[6,7,8]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

*Q2. (np.zeros() and np.ones())
Create the following using NumPy:
a) A 1D array of 8 zeros.
b) A 2D array of shape (4, 4) filled with ones.
c) A 3x3 matrix of zeros.
Print all arrays with proper labels.*

In [13]:
# Inport a Numpy as np
import numpy as np

In [14]:
# Creating A 1D array of 8 zeros.
Array1 = np.zeros(8)
Array1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# Creating A 2D array of shape (4, 4) filled with ones.
Array2 =np.ones(16).reshape(4,4)
Array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# Creating a A 3x3 matrix of zeros.
Array3 = np.zeros(9).reshape(3,3)
Array3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

*Q3. (np.arange())
Use np.arange() to create and print the following arrays:
a) Numbers from 0 to 20 (step 1).
b) Even numbers from 10 to 50.
c) Numbers from 5 to 100 with step of 5.*

In [18]:
# Numbers from 0 to 20 (step 1).
Array4 = np.arange(0,20)
Array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
# Even numbers from 10 to 50.
Array5 = np.arange(2,50,2)
Array5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [25]:
# Numbers from 5 to 100 with step of 5.
Array6 = np.arange(5,100,5)
Array6

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

*Q4. (np.linspace())
Use np.linspace() to create:
a) 10 equally spaced numbers between 0 and 5.
b) 15 equally spaced numbers between -10 and 10.
Print the arrays and their length.*

In [36]:
# 10 equally spaced numbers between 0 and 5.
Array7 =np.linspace(0,5,10)
print("Array:", Array7)
print("Length:", len(Array7))

Array: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10


In [37]:
# 15 equally spaced numbers between -10 and 10.
Array8 =np.linspace(-10,10,15)
print("Array:", Array8)
print("Length:", len(Array8))

Array: [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


*Q5. (Random Arrays)
Write a program to generate:
a) A 1D array of 10 random numbers between 0 and 1 using np.random.rand().
b) A 3x3 matrix of random numbers from standard normal distribution using
np.random.randn().*

In [40]:
# A 1D array of 10 random numbers between 0 and 1 using np.random.rand().
Array9 = np.random.rand(10)
Array9

array([0.66304963, 0.23508809, 0.41983886, 0.33720145, 0.50249808,
       0.62348085, 0.4295698 , 0.00513401, 0.67010961, 0.43198521])

In [42]:
# A 3x3 matrix of random numbers from standard normal distribution using np.random.randn().
Array10 = np.random.randn(3,3)
Array10

array([[ 0.15876959, -2.58532384, -0.93450729],
       [-0.55622479,  1.63386291,  0.41753905],
       [-0.08278132, -0.08348636,  0.76578984]])

In [54]:
# A 2D array (4x5) of random integers between 10 and 50 using np.random.randint().
Array11 = np.random.randint(10,50,size=(4,5))
Array11

array([[18, 44, 33, 30, 16],
       [46, 21, 39, 35, 13],
       [42, 22, 15, 30, 23],
       [24, 43, 36, 18, 31]])

*Q6. (Vectors and Basic Operations)
Create two vectors:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
Perform and print:
Addition
Subtraction
Element-wise multiplication
Dot product*

In [57]:
# Create two vectors:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

# Addition
print("Addition:", v1 + v2)

# Subtraction
print("Subtraction:", v1 - v2)

# Element-wise Multiplication
print("Element-wise Multiplication:", v1 * v2)

# Dot Product
print("Dot Product:", np.dot(v1, v2))

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56]
Dot Product: 100


*Q7. (Matrices and Operations)
Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform the following:
Matrix addition
Matrix multiplication (@ or np.dot())
Element-wise multiplication (*)
Print the results clearly.*

In [64]:
# Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

# Matrix addition
print("Matrix addition :\n",A+B)


# Matrix multiplication (@ or np.dot())
print("\nMatrix multiplication :\n", A@B)

# Element-wise multiplication (*) Print the results clearly.
print("\nElement-wise multiplication :\n",A*B)

Matrix addition :
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix multiplication :
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise multiplication :
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


*Q8. (Properties of Arrays)
Create a 4x4 matrix of random integers between 1 and 100.
Print:
Shape
Dimension (ndim)
Total number of elements (size)
Data type
Minimum and maximum values*

In [85]:
A = np.random.randint(1,100,size=(4,4))

print("Shape :",np.shape(A))
print("\nDimension :",np.ndim(A))
print("\nTotal number of elements :",np.size(A))
print("\nData type :",A.dtype)
print("\nMinimum values :",A.min())
print("\nmaximum values :",A.max())


Shape : (4, 4)

Dimension : 2

Total number of elements : 16

Data type : int64

Minimum values : 3

maximum values : 96


*Q9. (Combined - Random + Reshape + Statistics)
Generate a 1D array of 20 random integers between 1 and 50 using
np.random.randint().
Reshape it into a 4x5 matrix.
Print the sum, mean, and standard deviation of the matrix.
Find the maximum value in each row.*

In [144]:
# Generate a 1D array of 20 random integers between 1 and 50 using np.random.randint().
B = np.random.randint(1,50,size=(20))


In [145]:
# Original Array
print("\nOriginal Array :",B)


Original Array : [43 40 16 11 43 35 39 14 32 11 43  9 23 27 36 41 29 17  8 49]


In [146]:
# Reshape it into a 4x5 matrix.
B = B.reshape(4,5)

In [147]:
# sum
print("\nAddintion :",B.sum())


Addintion : 566


In [148]:
# Mean
print("\nmean :",B.mean())


mean : 28.3


In [149]:
# standard deviation
print("\nstandard deviation :",B.std())


standard deviation : 13.236691429507601


In [150]:
# Find the maximum value in each row.
print("\nMaximum value in each row:")
print(np.max(B,axis=1))


Maximum value in each row:
[43 39 43 49]


*Q10. (Mini Project - NumPy Application)
Create a Simple Statistics Calculator using NumPy:
Write a program that:
Asks the user how many numbers they want to generate.
Generates that many random numbers between 10 and 100 using
np.random.randint().
Stores them in a 1D array.
Prints:
The array
Mean, Median, Standard Deviation
Minimum and Maximum
Reshapes into a 2D array (if possible) and prints row-wise sum.
Use proper comments and exception handling where needed.*

In [151]:
import numpy as np

try:
    # Ask the user how many numbers to generate
    n = int(input("How many random numbers do you want to generate? : "))

    if n <= 0:
        print("Please enter a number greater than 0.")

    else:
        # Generate random numbers between 10 and 100
        arr = np.random.randint(10, 101, n)

        # Print the array
        print("\nGenerated Array:")
        print(arr)

        # Statistics
        print("\n----- Statistics -----")
        print("Mean :", np.mean(arr))
        print("Median :", np.median(arr))
        print("Standard Deviation :", np.std(arr))
        print("Minimum :", np.min(arr))
        print("Maximum :", np.max(arr))

        # Reshape into 2D array if possible
        print("\n----- 2D Matrix -----")

        rows = int(np.sqrt(n))

        if rows > 1 and n % rows == 0:
            cols = n // rows

            matrix = arr.reshape(rows, cols)

            print(matrix)

            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))

        else:
            print("Cannot reshape into a proper 2D matrix.")

except ValueError:
    print("Invalid Input! Please enter an integer.")

How many random numbers do you want to generate? : 6

Generated Array:
[87 31 31 53 41 31]

----- Statistics -----
Mean : 45.666666666666664
Median : 36.0
Standard Deviation : 20.121851030382093
Minimum : 31
Maximum : 87

----- 2D Matrix -----
[[87 31 31]
 [53 41 31]]

Row-wise Sum:
[149 125]
